Fix arithmetic operator precedence
opensearch-project/sql pull request #1172
Opened 2022-12-14 17:32 UTC by dai-chen

### Description

This PR fixed arithmetic operator precedence by reordering ANTLR grammar rules. I tried to reorder operator in `mathOperator` rule (Reference: https://github.com/antlr/grammars-v4/blob/master/sql/mysql/Positive-Technologies/MySqlParser.g4#L2598). However, it didn't work.

So finally I split the `mathExpressionAtom` rule and order them by precedence (Reference: https://github.com/crate/crate/blob/master/libs/sql-parser/src/main/antlr/SqlBaseParser.g4#L299).
 
### Issues Resolved

https://github.com/opensearch-project/sql/issues/293
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-12-14 19:34 UTC, Yury-Fridlyand requested changes
Please fix this for PPL too:
```
opensearchsql> source=people | eval test = 1 + 2 * 3 | fields `test`;
fetched rows / total rows = 1/1
+--------+
| test   |
|--------|
| 9      |
+--------+
```

2022-12-14 20:18 UTC, dai-chen commented
> Please fix this for PPL too:
> 
> ```
> opensearchsql> source=people | eval test = 1 + 2 * 3 | fields `test`;
> fetched rows / total rows = 1/1
> +--------+
> | test   |
> |--------|
> | 9      |
> +--------+
> ```

I missed it. Let me check.

2022-12-14 23:05 UTC, dai-chen commented
> > Please fix this for PPL too:
> > ```
> > opensearchsql> source=people | eval test = 1 + 2 * 3 | fields `test`;
> > fetched rows / total rows = 1/1
> > +--------+
> > | test   |
> > |--------|
> > | 9      |
> > +--------+
> > ```
> 
> I missed it. Let me check.

Fixed in https://github.com/opensearch-project/sql/pull/1172/commits/bac6f3a7c7cdae0418dcb45451d5fddaf2e521a0. I found that PPL expression doesn't support parentheses. I'm not sure if this is by design for other expressions like logical and comparison. I fixed this for arithmetic expression which is required by this precedence fix. Thanks!

2022-12-15 00:38 UTC, Yury-Fridlyand approved these changes

2022-12-16 03:39 UTC, penghuo approved these changes

2022-12-16 17:37 UTC, merged