Add release notes for v2.16.0
opensearch-project/sql pull request #2854
Opened 2024-07-23 23:25 UTC by dai-chen

### Description

Add release notes for OpenSearch 2.16.0 release.
 
### Issues Resolved

https://github.com/opensearch-project/sql/issues/2748
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-07-24 16:32 UTC, YANG-DB approved these changes

2024-07-24 17:11 UTC, ykmr1224 requested changes
Sorry for being late, can you add this one?
https://github.com/opensearch-project/sql/commit/e841266ddf3792ce0000a98c8aacbc3e922175f4

2024-07-24 18:38 UTC, rupal-bq approved these changes

2024-07-24 18:42 UTC, derek-ho submitted a review, later dismissed

2024-07-24 22:16 UTC, dai-chen commented
@ykmr1224 Added in https://github.com/opensearch-project/sql/pull/2854/commits/92d4a6f76eef62031ff66a2eea0159dada2278a3. Please approve again.

cc: @YANG-DB @rupal-bq

2024-07-25 16:58 UTC, rupal-bq approved these changes

2024-07-25 17:27 UTC, vamsi-amazon approved these changes

2024-07-25 18:15 UTC, ykmr1224 approved these changes

2024-07-25 18:28 UTC, merged