Change master node timeout to new API
opensearch-project/sql pull request #793
Opened 2022-08-30 20:23 UTC by dai-chen

Signed-off-by: Chen Dai <daichen@amazon.com>

### Description
Change `masterNodeTimeout` to new API `clusterManagerNodeTimeout`.
 
### Issues Resolved
https://github.com/opensearch-project/sql/issues/463
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-08-30 21:05 UTC, Yury-Fridlyand requested changes

2022-08-30 21:05 UTC, Yury-Fridlyand commented on plugin/src/main/java/org/opensearch/sql/plugin/rest/RestQuerySettingsAction.java
> +        "master_timeout", clusterUpdateSettingsRequest.clusterManagerNodeTimeout()));
should be `cluster_manager_timeout`

2022-08-30 22:24 UTC, dai-chen commented on plugin/src/main/java/org/opensearch/sql/plugin/rest/RestQuerySettingsAction.java
> +        "master_timeout", clusterUpdateSettingsRequest.clusterManagerNodeTimeout()));
missed it. fixing now. thanks!

2022-08-31 15:49 UTC, penghuo approved these changes

2022-09-01 22:34 UTC, anirudha approved these changes
Thanks

2022-09-01 22:44 UTC, merged